export const SLIDE_LIST_REQUEST = 'SLIDE_LIST_REQUEST'
export const SLIDE_LIST_SUCCESS = 'SLIDE_LIST_SUCCESS'
export const SLIDE_LIST_FAIL = 'SLIDE_LIST_FAIL'

export const ADD_SLIDE_REQUEST = 'ADD_SLIDE_REQUEST'
export const ADD_SLIDE_SUCCESS = 'ADD_SLIDE_SUCCESS'
export const ADD_SLIDE_FAIL = 'ADD_SLIDE_FAIL'
